### ISSUE TITLE
Endless redirect if not signed in to IdP

### ISSUE THREAD

**Issue by stile1201** [Noovolari/leapp#105]
**Describe the bug**
When my SSO session times out, Leapp opens the AWS SSO start URL in a new browser tab. AWS SSO redirects to my identity provider, which prompts for credentials, but Leapp immediatey opens another tab, and repeats.

**Leapp Version**
0.4.7

**To Reproduce**

1. Sign in to AWS SSO (via my identity provider)
2. Open Leapp
3. Leapp opens a browser tab, and successfully authenticates with AWS SSO.
4. Wait for my AWS SSO session to expire
5. Leapp opens a browser tab, which redirects to my identity provider, and then opens another tab, and another one, and does not successfully authenticate.
6. Closing Leapp and re-opening fixes the issue.

**Expected behavior**
When my AWS SSO session expires, Leapp should open a browser tab and re-authenticate successfully.

**Screenshots**
I can try to provide these if necessary.

**Desktop (please complete the following information):**

OS: macOS Catalina
OS Version: 10.15.7
Leapp Version: 0.4.7

**Additional context**
We federate to Keycloak as our identity provider for AWS SSO.

**Comment by ivan-sirosh** [comment]
the same for me

**Comment by andreacavagna01** [comment]
Thanks for reporting, I'm sorry for this inconvenience. 
Please can you describe the issue following the bug template?

It's important to me to reproduce the bug and fix it asap to have all the steps to reproduce it and the additional logs to get more information.

you can find them here: https://github.com/Noovolari/leapp#logs

**Describe the bug**
A clear and concise description of what the bug is.

**Leapp Version**
Add the version of your Leapp (you can find it under taskbar -> about or Leapp -> about on MacOS X)

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - OS Version [e.g. 22]
 - Leapp Version [e.g. 0.2.5]

**Additional context**
Add any other context about the problem here.

**Comment by andreacavagna01** [comment]
I will be happy to help. If any troubleshooting with your configuration is needed I will be in the [Slack workspace](https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q)

**Comment by PatrykMilewski** [comment]
Having the same issue. To reproduce:
1. Start Leapp normally.
2. Grant it an access to SSO.
4. Block the computer
5. Wait until SSO session expires (8 hours in my case)
5. Unblock the computer
6. Leapp automatically opens the browser for SSO revalidation
7. After some time (around 1-2 minutes), it opens another browser tab for SSO revalidation

If you leave it over the night, then it will open a lot of tabs. It was also noticed by my teammate.

I believe something is wrong with the logic for revalidating SSO session, as it should have some sort of maximum retries

**Comment by stile1201** [comment]
> 7. After some time (around 1-2 minutes), it opens another browser tab for SSO revalidation
> 
> If you leave it over the night, then it will open a lot of tabs. It was also noticed by my teammate.
> 

My experience is slightly different, in that it is not 1-2 minutes between it opening tabs - more like less than a second, so it quickly becomes dozens, even hundreds of tabs.

But yes, it's when the SSO session expires that it happens.

**Comment by stile1201** [comment]
Nice to see there's a fix, thanks! When do you plan to release?

**Comment by andreacavagna01** [comment]
Testing it right now, as soon as possible, sorry for the inconvenience

**Comment by stile1201** [comment]
No worries. Love the app, and appreciate the swift response!

**Comment by agponte** [comment]
I built and tested last night and woke to hundreds of tabs again.  Is there anything I can provide to help out?

**Comment by andreacavagna01** [comment]
Noisy infinite tab problem is fixed in version v0.5.0, now Leapp deactivate the session after the timeout expire
