### ISSUE TITLE
Version 0.5.3 renders Leapp useless - No longer can manage AWS accounts with profiles

### ISSUE THREAD

**Issue by caiola** [Noovolari/leapp#117]
**Describe the bug**
I do not want to update to the latest version because it does set the credentails profiles correctly in %userprofile%/.aws/credentials.

I have multiple profiles defined in Leapp so that it defines the [profile] configuration in %userprofile%/.aws/credentials.

When you click to set the active profile / credentials, it always sets in the [default] section in the file.
Also, you lost the ability to set multiple credentials active and only one can be set as [default]

**Leapp Version**
 0.5.3

**To Reproduce**
1. Create account and add a profile to it, click on the account to set active.
2. Only one can be set as default. It lost the ability to set multiple accounts.

**Expected behavior**
Set the account active and add the profile credentials to %userprofile%/.aws/credentials

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version [e.g. 10]
 - Leapp Version [e.g. 0.5.3]

**Comment by andreacavagna01** [comment]
Hi @caiola, we roll back to a previous version because of the auto-updater, and from 0.5.3 onward we removed the automatic update.

The rollback brought back the previous behavior in credentials generation and I’m currently working on re-enabling the named-profile feature for the next release.

If you’re interested or you want to build a version from scratch you can follow the work in progress on [this branch](https://github.com/Noovolari/leapp/tree/named-profile-refactor), until the release this branch will not be stable as Master branch.

This will be generally available in the next release.
For now, there is no method to use a specific version prior to 0.5.3.

For further details or any help, I can suggest you to join our Slack community

**Comment by andreacavagna01** [comment]
Named-profiles are back with the new Release v.0.6.0
