### ISSUE TITLE
Support Duo SSO Federation

### ISSUE THREAD

**Issue by zswanson** [Noovolari/leapp#121]
**Is your feature request related to a problem? Please describe.**
Support federation with Duo as an SSO provider

**Describe the solution you'd like**
Similar federation option as Okta or Google Suite when setting up Leapp

**Comment by andreacavagna01** [comment]
Hi @zswanson, the implementation of a new Service Provider like Duo is not currently in the Team roadmap, but the solution is pretty easy to implement.

As seen in this method, the callback function that catches the Duo SAML Response needs to be implemented:
https://github.com/Noovolari/leapp/blob/74ba2d10338da83b3182e798d551f6651d1af010/src/app/services/workspace.service.ts#L167

Then the federated Account with Duo will work.

I can help you in implementing it if you have any trouble with the Leapp code, but since I have not Duo as Identity Provider I'm not able to test this functionality.

If any help is needed to implement this solution or to try to contribute with Leapp, please [join our community](https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q) and I will be happy to assist you in implementing it!

**Comment by zswanson** [comment]
We'll take a look, I think from your pointer this looks fairly straight forward.

**Comment by andreacavagna01** [comment]
Need any help with this issue?

**Comment by zswanson** [comment]
Unfortunately we've been swamped in other areas and it was dependent on our
migration to duo which has kind of stalled out.
Happy to close this request and I can revisit sometime in the future

**Comment by andreacavagna01** [comment]
Nice! If you need any help in future implementing this feature, I can assist you in the programming part 👍

**Comment by pethron** [comment]
Closing since @zswanson doesn't need it anymore.
Feel free to reopen if a similar use case pops out.
