### ISSUE TITLE
Blank white screen on MacOS 0.5.3 version

### ISSUE THREAD

**Issue by shodo** [Noovolari/leapp#139]
**Describe the bug**
After installing and launching the app I cannot do anything cause it shows only a window with a blank white screen. 

**Leapp Version**
0.5.3

**To Reproduce**
1. Install the 0.5.3 on MacOs Catalina with the dmg installer
2. Open the app
3. Notice the blank white screen and app unresponsiveness

**Expected behavior**
App shows all controls and it's responsive

**Screenshots**
<img width="569" alt="Screenshot 2021-07-01 at 11 57 46" src="https://user-images.githubusercontent.com/6939800/124105614-ad5b6e80-da63-11eb-83ed-7415fe771cdd.png">

**Desktop (please complete the following information):**
 - OS: macOs Catalina
 - OS Version 10.15.7
 - Leapp Version 0.5.3

**Additional context**
I tried to launch from terminal and I receive this error:
```
Checking for update
Found version 0.6.0 (url: Leapp-0.6.0-mac.zip, Leapp-0.6.0.dmg)
(node:9209) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.send (electron/js2c/renderer_init.js:103:332)
    at electron/js2c/renderer_init.js:99:343
(node:9209) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9209) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Another thing: I previously installed version 0.6.0 without issues, but I cannot use it cause it asks different settings for the federated configuration in respect of what I was instructed to put in the 0.5.3 version.

**Comment by andreacavagna01** [comment]
> Another thing: I previously installed version 0.6.0 without issues, but I cannot use it cause it asks different settings for the federated configuration in respect of what I was instructed to put in the 0.5.3 version.

The configuration file inside the `./Leapp/Leapp-lock.json` is not retro-compatible with the v0.5.3 version.

The information to insert from the last version are changed:
- in version v.0.5.3 the information needed was:
  - `accountNumber`
  - `role`
- in version v0.6.0 you just need to add the information: 
  - `roleArn` : how to compose a role Arn with the previous information? -> `arn:aws:iam::YOUR_ACCOUNT_NUMBER:role/YOUR_ROLE`

you can follow this guide on how to compose this information:

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html


I can suggest you use the v0.6.0 version with this updated information. 

I'm closing these issues because is not referring to the last version of the project and it is a retro-compatibility problem.
