### ISSUE TITLE
MFA prompt on chained role and other chained role issues

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#143]
There are a number of things that are not clear to me about how to set up role chaining. The wiki entries ([here](https://github.com/Noovolari/leapp/wiki/use-cases#aws-truster-access) and [here](https://github.com/Noovolari/leapp/wiki/create-a-truster-strategy-with-leapp)) appear out-of-date, but I think I have set it up properly. Still, it does not work the way I expect.

I have a "source profile" configured in my `$AWS_CONFIG_FILE` and a cross-account chained role. Prior to using Leapp, I would use `aws-vault` to generate session credentials for the source profile (entering the MFA token once per 8 hour session), and then I could simply change `$AWS_PROFILE` to the chained role profile and it would work.

```ini
[profile source]
region = us-west-2
default_region = us-west-2
; account 123123123123

[profile nuru]
region = us-west-2
mfa_serial = arn:aws:iam::123123123123:mfa/nuru@example.com
role_arn = arn:aws:iam::333333333333:role/nuru
source_profile = source
```

Ideally, I would expect that when I click on my chained profile in Leapp, it would do everything needed to make the chained role available. Instead, if all I do is click on the chained role, it is marked active, but the `aws` CLI complains 
```text
The source profile "source" must have credentials.
```

If I first click the "source" session, I am prompted for my MFA token, and if I give it, then the "source" session becomes active. As I said, that used to be all I needed to do, but now when I set `AWS_PROFILE=nuru` I get prompted for the MFA on the command line once I try to do anything. 

Clicking on the chained session makes it appear active in the UI, but does not seem to have any real effect. It does not prompt me for MFA nor does it remove the need for me to type the MFA code on the command line.

If I have only the source session active, and the type in the MFA code after setting `AWS_PROFILE=nuru`, some commands work (e.g. `aws s3api list-buckets`), but if I then try to assume another role via the command line (which used to work fine), I get this error:

```text
Error creating AWS session: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, 
but AssumeRoleTokenProvider session option not set.
```

To get that working, I need to activate the chained role session in Leapp. 

**Leapp Version**
0.6.0

**To Reproduce**

Before:
1. `aws-vault` login as `source`
2.  Provide MFA token for `source`

With Leapp:
1. Click `source` session
2. Provide MFA token for `source`
3. Click `chained` session
4. Provide MFA token for `chained`

**Expected behavior**
A click on a session should enable access to the profile named in the session.

With Leapp:
1. Click `chained` session
2. Provide MFA token for `source`

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version: 10.15.7
 - Leapp Version: 0.6.0

**Comment by andreacavagna01** [comment]
Please, let Leapp manage profiles for you. Don't configure AWS named profiles in your `~/.aws/config` file. 
Otherwise, you may encounter some issues. 
By now Leapp manages only AWS named profiles in the `~/.aws/credentials` file.


Leapp manages MFA device in-App and generated only short-lived credentials from that information, so you don't have to add MFA device arn for each profile in `~/.aws/config`; the only thing you need is to provide an MFA device for the IAM user with the MFA enabled.

All other Chained IAM Roles you are going to create with Leapp will automatically prompt MFA authentication from the parent IAM User linked to them.

MFA is not prompted again until your MFA access token does not expire.

You can follow the guides here:
- https://aws.amazon.com/blogs/security/how-do-i-protect-cross-account-access-using-mfa-2/
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html


If any other help is needed, please join our community and I will be happy to help you:
https://join.slack.com/t/noovolari/shared_invite/zt-opn8q98k-HDZfpJ2_2U3RdTnN~u_B~Q

**Comment by ericvilla** [comment]
After a review of the Issue, I think we can consider it closed; as far as now, the described approach is quite different from the one provided by Leapp. 

If needed, please feel free to re-open the issue or have a discussion about the topic. Thank you!
