### ISSUE TITLE
White blank page on startup

### ISSUE THREAD

**Issue by shifr** [Noovolari/leapp#204]
**Describe the bug**
Hello! Thanks for the great and easy-to-use tool but I've faced an issue lately.
It worked before but now when I open the application I see only a blank white page (screenshot attached)

**Leapp Version**
0.7.3, 0.7.4, 0.8.0

**To Reproduce**
1. Open the app

**Expected behavior**
The app opens and I can see a list of my AWS accounts

**Screenshots**
<img width="517" alt="Screen Shot 2021-12-03 at 12 20 04" src="https://user-images.githubusercontent.com/3635912/144586471-a129da70-f870-4297-b3aa-2645fb3e92bd.png">
<img width="522" alt="Screen Shot 2021-12-03 at 12 20 21" src="https://user-images.githubusercontent.com/3635912/144586504-97fcc0b0-e701-4bd6-b380-fa4a99a16884.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - OS Version 11.6.1
 - Leapp Version 0.8.0

**Additional context**
I can see `Error: Malformed UTF-8` in the console in developer tools (screenshot)

**Comment by urz9999** [comment]
Hi @shifr, thank you for trying Leapp! It is a problem due to the incompatibility of a very old configuration file with the new version. Leapp has a migration service that tries to modify the leapp-lock file to be always up to date, but sometimes perfect conversion is not possible. Try to make a backup of your old leapp-lock.json file in ~/.Leapp calling it maybe leapp-lock.json.bkp and try to run the application again.

**Comment by shifr** [comment]
@urz9999 it worked! Thank you!
Is there any documentation that could be missed when I was trying to figure out what's happening?

**Comment by urz9999** [comment]
Not in this case, it is mainly due to the configuration file being ported from the earliest versions of Leapp which, sometimes, make it difficult to migrate to the new versions. We are currently working on a revamped migration mechanism that hopefully will make transitions from version to version more robust in terms of the configuration file.
