### ISSUE TITLE
v0.9.0 complaints and suggested solutions

### ISSUE THREAD

**Issue by Nuru** [Noovolari/leapp#229]
I greatly appreciate you providing this tool; I find it very helpful and use it every day. However, because I use it every day, I care more about how well it works. Please consider the following complaints and suggested solutions.

Although each of these should probably be a separate issue, I thought I'd combine them here to keep the issue count down and because probably some of them you are not going to want to do anything about. Feel free to clone new issues from this one if you find it helpful.

Upgrading from 0.7.4 to 0.9.0, I have the following complaints:

- #202 still a problem: all sessions reverted to "default" profile
- After logging in, I continually get `t.expired is not a function` error
- I really do not like that it now requires 2 clicks to log in or log out. Even worse, if the session is at the bottom of the list, then to log in requires a click to bring up the pop-up menu, then a mouse reposition to find the "Start Session" menu, then another click. Logging in and logging out is the most used function, so the UI should be optimized for it. They should be very easy 1-click operations.
- While the sort and search features are nice, I would still prefer the ability to manually set the unsorted order of sessions. Review how the [Netflix DVD queue](https://dvd.netflix.com/Queue) works for a good example of how to present the UI for this. For implementation help, see this [example from Draggable](https://shopify.github.io/draggable/examples/simple-list.html) or this [example](https://isocra.com/2008/02/table-drag-and-drop-jquery-plugin/) using the [table drag and drop plugin](https://github.com/isocra/TableDnD/) for [jQuery](https://jquery.com/).
- Similarly, I would like to be able to control which sessions show up in the Leapp menu (from the menu bar) and in what order, preferably separately from the order they are displayed in the main window. Right now it is in some order I do not recognize, and the sessions I want to use most often are not in the list. Pinning a session in the main window does not seem to affect the order of the menu either.
- It remains an issue that if I log into a session from the bottom of the list (where the top of the list has scrolled out of view), I do not see the results of the session logging in automatically. I think there should be a fixed frame at the top of the window that shows logged in (and maybe recently logged out) sessions.

**Comment by randall-emed** [comment]
Same here, the `t.expired is not a function` really hinders the usability, since it buries all the bottom buttons.

**Comment by ericvilla** [comment]
Thank you very much @Nuru for the thorough feedback, it's really appreciated!

I'll let @andreacavagna01 and @urz9999 give a response about UX/UI related issue; just let me say that you can double click directly on the session's card to activate it, instead of moving the mouse to the pop-up menu.

For what concerns the first point we have to double-check the migration logic. We're going to test a migration from version 0.7.4 to 0.9.0. To reproduce your situation, may I ask you what are the type of sessions you set up in the 0.7.4 version before upgrading to 0.8.0? Please provide this info in the #202 issue.

I think `t.expired is not a function` is a problem related to migration too, cause it may be not able to deserialize an object that corresponds to an old version of the configuration file. We'll check it and come back to you with more details.

Thank you @Nuru @randall-emed!

**Comment by urz9999** [comment]
I would also add that you can right-click on a session everywhere to bring the contextual menu up with the most commonly used actions. 

For the taskbar, we are working on releasing a custom-designed one with more features than the standard native one.

Regarding the problem related to t.expired is not a function: it is quite easy to test also on your side; just make a backup of your Leapp-lock.json file and start fresh by adding any kind of session anew. Then wait and see if the error occurs, if not, most probably is related to what @ericvilla said.

In the meantime, we'll check your suggestions for a custom-ordered list.


Thanks!

**Comment by ericvilla** [comment]
https://github.com/Noovolari/leapp/issues/202#issuecomment-1055445977: related to the profile issue :smiley:

**Comment by ericvilla** [comment]
@Nuru I've just reproduced the following scenario:

* install and run Leapp 0.7.4;
* configured an AWS SSO integration;
* installed and run Leapp 0.8.0 (as you described in #202);
* re-install and run Leapp 0.7.4;
* install and run Leapp 0.9.0;
* activate a session to test credentials rotation logic.

Credentials rotation seems to work properly. I didn't get a `t.expired is not a function` error.
I configured an AWS SSO integration, so Sessions are _AWS SSO Role_ ones.

Let me know what kind of Sessions have you configured so that I can properly reproduce your specific scenario and proceed with further investigation.

**Comment by Nuru** [comment]
@urz9999 wrote:
> I would also add that you can right-click on a session everywhere to bring the contextual menu up with the most commonly used actions.

That still means that to start or end a session I need 2 clicks, and now it is a right-click, move to find menu item, left-click. Still more work than it used to be or should be for the most important feature/usage.
 

@ericvilla 
> Regarding the problem related to t.expired is not a function: it is quite easy to test also on your side; just make a backup of your Leapp-lock.json file and start fresh by adding any kind of session anew. Then wait and see if the error occurs, if not, most probably is related to what @ericvilla said.

The `t.expired` problem seems to be fixed, along with #202, in v0.10.0. Thank you.

**Comment by andreacavagna01** [comment]
> That still means that to start or end a session I need 2 clicks, and now it is a right-click, move to find menu item, left-click. Still more work than it used to be or should be for the most important feature/usage.

Now, with v0.10.0. whenever you over a session, the Provider icon change with a play button and you can start a Session within a click. Which is THE critical feature of Leapp I think, as you said.

Thanks for the contribution @Nuru

**Comment by Nuru** [comment]
@andreacavagna01 Thank you, hovering over the session and getting a start/stop button is an acceptable solution. On the other hand, now (v0.11.0) when you hover over the session and click play/stop, it is a problem that the status indicator (grey, orange, or green disk) becomes an ellipsis to indicate a submenu is available. 

![image](https://user-images.githubusercontent.com/2793313/161245954-10a77eb3-d37f-4987-b93a-c3ca250ff676.png)

So now I hover, click play/start, and have to move the pointer away to see if the login was successful or not. It's also a little annoying that the primary option (stop/start) is about as far away as possible from all the other options accessible via the submenu.

Suggested options:
1. Have the start/stop button display the submenu when right-clicked.
2. Enlarge the status indicator so that it is big enough to contain the ellipsis, then show the ellipsis inside the status indicator rather than have it replace the status indicator.

**Comment by andreacavagna01** [comment]
close due to inactivity
