### ISSUE TITLE
Error: "Can not read properties of null" when trying to start a SSO session

### ISSUE THREAD

**Issue by endersonmaia** [Noovolari/leapp#253]
**Describe the bug**

After upgrading to 0.11.0, I get this error when trying to start a session:

![leapp-error](https://user-images.githubusercontent.com/370/162981446-68603149-8a18-4955-8cdc-9cdc9e7e2af1.png)

**Leapp Version**

0.11.0

**To Reproduce**

Start Leapp, and try to start a Session.

**Expected behavior**

Login screen for SSO should come, but if fails and then I get the error.

**Desktop (please complete the following information):**

 - OS:  Linux 
 - OS Version: 20.04.4 LTS (Focal Fossa)
 - Leapp Version: 0.11.0

**Additional context**

I also get the error mentioned at #249, before getting to this one.

**Comment by ericvilla** [comment]
Hi @endersonmaia, thank you for reporting this issue! 

It's probably a retro-compatibility issue due to a change in how AWS SSO configuration is stored. We need to further investigate it. 

You can fix it the "hard way" by backing up the ~.Leapp/Leapp-lock.json file so that Leapp recreates it from scratch (you'll loose your current configuration). Otherwise, you can try to delete the AWS SSO integration and create it again.

**Comment by endersonmaia** [comment]
> Otherwise, you can try to delete the AWS SSO integration and create it again.

That solved. Thanks!

**Comment by ericvilla** [comment]
I'm going to close this issue as we found a way to work around it. It's a retro-compatibility issue, so ask to re-open it if you fall in the same scenario. Thanks!
