### ISSUE TITLE
How to use AWS AssumeRole with MFA

### ISSUE THREAD

**Issue by Mattie112** [Noovolari/leapp#254]
Sorry, this is not really a bug nor a feature request.

My colleague is experimenting with `aws-vault` so we can enforce MFA for our cluster. He has a aws config file like this:
```
[profile xx-xx-prod]
role_arn=arn:aws:iam::xx:role/xxAdminAccessForLogin
source_profile=xx-login
mfa_serial=arn:aws:iam::xx:mfa/XXXXXXXXXXX
region=eu-west-1

[profile xx-xx-staging]
role_arn=arn:aws:iam::xx:role/xxAdminAccessForLogin
source_profile=xx-login
mfa_serial=arn:aws:iam::xx:mfa/XXXXXXXXXXXXXXXXXX
region=eu-central-1

[profile xx-login]
#yes, nothing here
```
He can then use this to do `terraform` commands and for example start Lens through:
`aws-vault exec xx-xx-staging -- kontena-lens --context=arn:aws:eks:eu-central-1:xx:cluster/xx-xx-staging`

However I don't really like this as this prevents the option from having multiple clusters open in one Lens window. You would need to restart it every time.

So: then I found Leapp. If I understand it correctly this should solve the problem described above. However I don't really understand how to set it up.

First I add a session for the 'login' account:
![image](https://user-images.githubusercontent.com/662896/163181441-8b451a59-4980-4fbb-804b-67afd4337d9b.png)

When I start that session I get asked for a MFA serial and then it succeeds.

Then I want to add the account I use to "AssumeRole":

![image](https://user-images.githubusercontent.com/662896/163181789-4a4151eb-372a-490b-8211-9e4d1832dcad.png)

I can also create/start this session with no problem. I do see credentials in `~/.aws/credentials`.
However when I want to run a `terraform apply` for example I get this error:

```
╷
│ Error: Kubernetes cluster unreachable: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
│ 
│ 
╵
╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain
│ caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
│ SharedCredsLoad: failed to load profile, .
│ EC2RoleRequestError: no EC2 instance role found
│ caused by: RequestError: send request failed
│ caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│ 
│ 
│   with module.shared.provider["registry.terraform.io/hashicorp/aws"],
│   on ../shared/main.tf line 41, in provider "aws":
│   41: provider "aws" {
│ 


```

I cannot post the entire terraform files but I think this is the relevant part:

```
terraform {
  backend "s3" {
    bucket  = "xx-terraform-state-xx-staging"
    key     = "network/terraform.tfstate"
    region  = "eu-central-1"
    profile="xx-xx-staging"
  }

  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.72.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
    profile="xx-xx-staging"
}

```
If I remove the profile from the terraform files and run init I get:

```
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

So I am hoping that there are some people here that have some experience and can give some pointers. Can we even use Leapp to solve the problem as described? I'm I using the wrong config? I don't really understand how it should work.

edit:
incuded the wrong error

**Comment by Mattie112** [comment]
Yeah that is kinda the problem I have indeed. However I thought that Leapp could fix this for my by simply giving access-tokens in the credentials file. In the Lens example: If I use an account that has direct access (without AssumeRole) then Lens just work with whatever is in the credentials file.

But perhaps I'm the first one wanting to use Leapp for this?

For example https://github.com/lensapp/lens/issues/208#issuecomment-636612354 lists how it should/could work with the credentials file. And as Leapp fills that file with tokens then it should work right?

I do now also see that someone there is recommending Leapp so I will also leave a message there to ask how that could be done.

**Comment by pethron** [comment]
Seems more like a Lens related problem, but it needs further investigation on how it reads the credentials file. I'm wondering if using multiple clusters with different credentials is supported because if they rely on the environment variables there is no way to pass more than one profile.

Even if you're the first to ask for something like this I think it would be an awesome addition for developers workflow. I'm no k8s expert but segregating clusters under different accounts (thus different set of credentials) I think it's quite the right approach. Wondering if that's how Lens was intended to be used.

**Comment by Mattie112** [comment]
Yeah might be a Lens thing but really I did not came as far as lens :) I need to run `terraform apply` to get a kubeconfig file I can use for Lens to connect to my cluster. But that is already not working. I'm guessing due to not using the correct profiles (because it can't find credentials) but yeah I don't really know how to trace this.

Still hoping someone uses it like this and has some pointers :)

**Comment by pethron** [comment]
If you want you can join our slack channel and we'll try to figure out the next steps together, link is on top of readme.

**Comment by Mattie112** [comment]
Yes that would be great :) What time would be best (I'm in UTC+2)? Today is a bit busy but perhaps tomorrow?

**Comment by Nuru** [comment]
@Mattie112 "Assume Role" means different things in different contexts. I'm not quite sure I know what you are talking about, so I will just give a short primer on the whole topic.


Whether or not you are using the `aws` CLI or other tools that work with AWS, credentials are handled relatively consistently via the AWS SDK (published as a library in several programming languages and thereby incorporated into most programs designed to work with AWS). Once you [configure the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) correctly, all the other tools should work, too.

The `$AWS_CONFIG_FILE` (by default `$HOME/.aws/config`) contains _profiles_ which specify (among other things) what AWS IAM Role to assume when using that profile and where to get the credentials that allow you to use that profile. I categorize these profiles into what I call "Primary" and "Derived" profiles. (I don't think AWS has terminology for this, so I invented my own. If they do and someone would educate me about it, I will use theirs if it is not too confusing.)

### First, lets go over everything without MFA:

- A Primary profile has credentials provided directly. When you (heaven forbid!) add AWS access keys into the profile or (much more securely) log in via Leapp, Leapp provides the credentials for the profile you specify in the Leapp session. `aws-vault` does the same kind of thing. (AWS SSO does, too, although a bit differently, and usually administrators of AWS SSO do not configure it in a way that lets you "assume" roles but instead configure it so that you can log into any of a number of Primary profiles, so check with your administrator if you are logging in via AWS SSO.) The main thing is that a Primary profile does _not_ have a `source_profile` entry.
- A Derived profile _does_ have a `source_profile` entry. It does not get credentials on its own, but instead it gets credentials from the source profile it references. To use a derived profile, the source profile has to have valid credentials, and it has to be allowed to assume the role specified in the Derived profile. Note that it is _not_ a requirement that the source profile be a Primary profile. The source profile can be another Derived profile; all that matters is that the chain of source profiles end at a role with valid credentials and that at every step in the chain, the source profile is allowed to assume the role specified in the Derived profile that references it.

You should only use Leapp (or `aws-vault`) to log into Primary profiles, and it is not required to have your Primary profiles included in your `$AWS_CONFIG_FILE`. The AWS SDK provides a separate file, `$AWS_SHARED_CREDENTIALS_FILE` (by default `$HOME/.aws/credentials`) where Leapp and other credential providers put the required profile information, including session credentials. Once logged into a Primary profile, any tool should be able to use that profile or any Derived profile simply by specifying which profile to use (usually by setting the AWS_PROFILE environment variable via `export AWS_PROFILE=profile-name` or via a command line flag, configuration string, or configuration file, such as in the case of `kubectl` via the `users.user.exec.env` section of the `$KUBECONFIG` file).

Just as you might not want to put your Primary profiles in your `$AWS_CONFIG_FILE`, I recommend you do not put any of your Derived profiles in Leapp. You might want to have your Primary profile in your `$AWS_CONFIG_FILE` so you can set CLI defaults or your default AWS region, but I can think of no reason to put Derived profiles in Leapp. Put them in the standard `$AWS_CONFIG_FILE` and they should work fine automatically, guarded by your login/logout of your Primary profile.

### Adding MFA

Now, best practice, you want everything protected by MFA. Great, easy, Leapp has you covered (except for not allowing you to edit sessions yet ☹️) Re-Create your Primary profile in Leapp, this time configuring in your MFA device. (Logging in via SAML or AWS SSO? Don't worry, as long as they are requiring MFA, you're good.)

Now everything should magically work as before, except every once in a while Leapp will prompt you for a new MFA token.

**There is one catch**. The AWS documentation and examples are confusing. In this scenario it is important that you _do not include `mfa_serial` in the Derived profile configuration._ The use case for having `mfa_serial` in the Derived profile is if you did not use MFA to authenticate to your Primary profile. In that rare case, the Derived profile really turns into a sort of Primary profile, because it is responsible for providing a credential (the MFA token) that the source profile does not have. That is when you need `mfa_serial` in the Derived profile and when you should put it in Leapp instead of just the `$AWS_CONFIG_FILE`.

If you put `mfa_serial` in your Derived profile, you will repeatedly and needlessly be prompted for an MFA token every time you assume the role, which, because it is a chained role, will be at least once an hour, and that prompt may not be visible because it is coming from the AWS SDK. With your Primary profile you only get prompted when your session expires, which can be as long as 12 hours.

### OP's specific case
In your case, @Mattie112:
- remove `mfa_serial` from `xx-xx-prod` and `xx-xx-staging`
- remove `xx-xx-prod` and `xx-xx-staging` sessions from Leapp
- Log into `xx-login` via Leapp with MFA

Pretty much everything else should work. You control what role is active via the `$AWS_PROFILE` shell environment variable or other "profile" setting available depending on the command/application you are using.

**Comment by Mattie112** [comment]
@Nuru thank you so much for this great explanation it really makes it a lot clearer for me :)

So I went around and tried the things you suggested:

- I now have a single `xx-login` profile in Leapp (with MFA)
- My $AWS_CONFIG_FILE as the 'derived' profiles (that indeed was where I used the term 'assume role' for) now contain:
```
[profile xx-xx-prod]
    role_arn=arn:aws:iam::xx:role/xxAdminAccessForLogin
    source_profile = xx-login
    region = eu-west-1

[profile xx-xx-staging]
    role_arn=arn:aws:iam::xx:role/xxAdminAccessForLogin
    source_profile = xx-login
    region = eu-central-1
```

My `main.tf` contains the profile
```
provider "aws" {
  region = "eu-central-1"
  profile = "xx-xx-staging"
}
```

However when running a `terraform apply` I would still get the error as listed in the OP (the first one).

Then I noticed your comment on `$AWS_PROFILE`  and indeed if I first set that (to `xx-xx-staging` or `xx-xx-prod` THEN I can run `terraform apply`). So at least that part works! Adding the profile to the `main.tf` does not seem to work but perhaps I have to read a bit more on where it is expected.

Now if I regenerete my kubeconfig with `aws eks update-kubeconfig --name xx-xx-prod` and `aws eks update-kubeconfig --name xx-xx-staging` I get a single kubeconfig file in my homedir with both clusters. Just opening Lens (without any special stuff) and these clusters work perfectly!

So yeah I seem to be 90% of the way and I'm really exited that it works so far. If I stop the session I can no longer access my stuff through Lens and if I start it again (MFA was not asked this time but assuming it is valid for some time) then it works fine.

So again: thank you for your help. I'll be looking into this in the next days to see if I can get the final things to work :)

Also:
All the stuff above was tested on Windows 11, will be trying it out on Linux (Ubuntu) when I get back into the office.

**Comment by Nuru** [comment]
@Mattie112 Yes, Lens works best with one `$KUBECONFIG` file per cluster, due to the cluster "context" setting only allowing one cluster to be active at a time.

I don't know what to tell you about the Terraform. Your OP has the correct `profile` setting for the backend and provider, and it should work fine. I use it all the time. It is possible Terraform is not finding your `$AWS_CONFIG_FILE` where it expects it to be (or you are running a really old version of Terraform).

**Comment by Mattie112** [comment]
Yeah not sure, for now I can also just remove the profile from the terraform files and just use the `AWS_PROFILE` env variable it works perfectly with that.

Also tested it today on Linux/Ubunbu seem to be working fine. Will be using it for some time and report back what I find :)

**Comment by andreacavagna01** [comment]
I can clarify this issue as closed, a big thank you to @Mattie112 and @Nuru!

Documentation and a blog post about Leapp and Lens authentication could be the conversation's outcome!

we will close when the documentation of Lens is made

**Comment by Mattie112** [comment]
Yes feel free to close, everything is working fine,

`AWS_PROFILE=some-profile terraform apply`

works great!
