### ISSUE TITLE
AWS credentials submenu / options feature in aws sso integration

### ISSUE THREAD

**Issue by kholisrag** [Noovolari/leapp#325]
**Is your feature request related to a problem? Please describe.**
When we're working on multiple subaccount with AWS SSO, we can export aws creds(env vars) per terminal session using aws creds that shown in the AWS SSO Webpage

**Describe the solution you'd like**
Leapp can shown individual aws credentials environment variable in the submenu of the application

**Describe alternatives you've considered**
using aws profile, but this ultimately lead to dangerous things if we work on multiple subaccount if we forgot to change the `--profile` flag value / default profile

or using https://github.com/jaxxstorm/aws-sso-creds

**Additional context**
Leapp able to shown aws credentials like : 
![Screenshot_2022-08-29_16-24-04](https://user-images.githubusercontent.com/4683704/187169483-623ab1f8-bfc8-4a55-bff4-e76f44a90e8e.png)

**Comment by andreacavagna01** [comment]
this is exactly a Plugin of Leapp; that's why [we introduced the plugin system](https://docs.leapp.cloud/0.14.2/plugins/plugins-introduction/) in the last few days!

I think @hoegertn is working on it with his plugin: https://github.com/taimos/leapp-plugin-shellcreds

in the next releases, we will have a plugin hub on the website to search for the plugin you need

**Comment by hoegertn** [comment]
Yes, this is exactly what my plugin is doing: Putting the Bash exports into the clipboard.

**Comment by kholisrag** [comment]
how to install yours plugins @hoegertn , seem like I follow the manual install way but still failed
