### ISSUE TITLE
Okta as Identity Provider

### ISSUE THREAD

**Issue by ivan-sukhomlyn** [Noovolari/leapp#54]
First of all, I like your idea. Looks like it's a really useful solution for multi-account access.

**Is your feature request related to a problem? Please describe.**
Currently, Leapp doesn't support another IdP except for AWS SSO and Google.

**Describe the solution you'd like**
Support Okta as IdP provider for temporary credentials fetching and using with the app

**Comment by ericvilla** [comment]
Hi @ivan-sukhomlyn, that's definitively something we're going to address in the next releases. We just forgot to add it to the roadmap: [there](https://github.com/Noovolari/leapp/projects/4) it is!

**Comment by ivan-sukhomlyn** [comment]
Hi @ericvilla 
Cool! Thanks
Looking forward to new releases

**Comment by andreacavagna01** [comment]
added in v0.4.5

**Comment by andreacavagna01** [comment]
Now You can each Federated Okta account to Leapp as a Federated Account with the Okta Idp URL, was that the enhancement @ivan-sukhomlyn ? 
There is someone that is using the **okta-aws-sso** or has any documentation on their APIs, it will be great to implement a thing like AWS SSO where the session will be auto-filled by the App.

**Comment by ivan-sukhomlyn** [comment]
hello @andreacavagna01 
It works fine. Thank you!

But, the IAM IdP ARN is a mandatory field for the **Federated Access Strategy** configuration adding.
![image](https://user-images.githubusercontent.com/55390366/108728142-f50c3f80-7531-11eb-9ee2-3f0e64771ad1.png)

An end-user usually doesn't have access to any information related to IdP configuration at AWS.
Also, I think it's really not required for Okta users, for example. A user can get temporary credentials without IdP ARN.

**Comment by andreacavagna01** [comment]
the Idp arn sadly is not a mandatory field:
it is a required field in the `assumeRoleWithSAML` call of the AWS SDK.

I know that information is not a piece of information that an end-user will have normally, but, for your use case, I think that the Okta is not used as a federated method to access AWS Cloud, but instead, as an App to manage Access in the AWS Environment, as AWS Single Sign-On does for AWS?

Is that correct?

With this method the IDP ARN will be mandatory I think, but it is because you are using a "Portal Url" and not an Identity Provider Url

Sadly I'm not a pro in Okta since I'm not using it.

**Comment by ericvilla** [comment]
Hi everyone,

if you're dealing with an IdP federated with AWS using SAML 2.0 protocol then you'll definitively need IdP ARN definition, since it is the "ambassador" of the SAML application on the AWS side. As @andreacavagna01 said, IdP ARN is not mandatory if you're connecting using Okta APIs, as AWS SSO does.

**Comment by ivan-sukhomlyn** [comment]
yes, I would like to connect to the AWS Console and configure a local AWS CLI profile through Okta as my SSO provider for Federated Login to AWS.

This configuration is pretty the same as described in Okta documentation:
1. https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Service
2. https://help.okta.com/en/prod/Content/Topics/DeploymentGuides/AWS/aws-about-integration.htm

In this case, AWS IdP ARN is not necessary for a user, but currently, it's mandatory at the application.

So, it would be nice if AWS IdP ARN would **not be a mandatory field** for the AWS Federated Access config in the Leapp application.

**Comment by andreacavagna01** [comment]
exactly, that's the Okta Aws App, not the Okta federation with an identity provider. 

I think most of the end-users are using the Okta AWS App for accessing Aws accounts, and that configuration is, inside the leap App configured as an Integration, but, sadly this is still not implemented.

From today we are supporting the federation only, we will work with the APIs of the Okta AWS App to manage also the integration and the automatic fill of all the available Aws Account in the app, to the end-users.


Also, @ivan-sukhomlyn, thanks for this documentation, I will check on it as soon as possible to implement it, Can I text you if I need any help?

**Comment by ivan-sukhomlyn** [comment]
AWS Okta Application works in pair with AWS SAML IdP created at IAM service for authentication federation and role assignment to an end-user.

@andreacavagna01 Yes, of course, you can mention me in the comment further :)
Thanks for clarifying and your work guys!
