### ISSUE TITLE
Show Instance Name for SSM Sessions

### ISSUE THREAD

**Issue by e-moshaya** [Noovolari/leapp#56]
Currently, when I want to try to start a SSM session, I get a list of instances by instance IDs. I would like to know the name of each instance id as our instances are immutable. Can you update the returned list to include the instance names derived from the Name tag?

![image](https://user-images.githubusercontent.com/44640934/104473638-16821f00-55b5-11eb-9001-5daaa9d62938.png)

**Comment by ericvilla** [comment]
Sure @e-moshaya, that could be extremely useful. As far as know, we only provide instances' id since this is what we can collect from AWS SSM API. Given these instances' ids, we have to invoke the AWS EC2 API to obtain names. I will add it to the roadmap, since it will enhance Leapp's overall experience. I'm going to contact AWS SSM team to understand if it is possible to include this information in response to the AWS SSM APIs invokation. I hope it makes sense to you, and thanks for your feedback!

**Comment by ericvilla** [comment]
Hi @e-moshaya, we solved this problem in the new [v0.4.1 version](https://github.com/Noovolari/leapp/projects/5). I think we can close the issue. Let us know if everything works fine

**Comment by andreacavagna01** [comment]
added in v0.6.0
